config/routes.rb
Nepusacica::Application.routes.draw do

  resources :opinions

  match 'caffes/index.json' => 'caffes#index'
  match 'caffes/search' => 'caffes#search'
  match 'caffes/search/:address' => 'caffes#search'
  resources :caffes

  root :to => 'caffes#index'

end

app/models/caffe.rb
class Caffe < ActiveRecord::Base
  attr_accessible :address, :name, :latitude, :longitude, :gmaps
  acts_as_gmappable

  has_many :opinions do
    def total_rating
      sum(:rating)
    end
  end

  def gmaps4rails_address
    address
  end

  def gmaps4rails_infowindow
      "#{name}"
  end

end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
  attr_accessible :caffe_id, :comment, :rating
  belongs_to :caffe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/caffes_controller.rb
class CaffesController < ApplicationController
  # GET /caffes
  # GET /caffes.json
  

  def index
    range = 0.01
    
    if !params[:latitude].blank? and !params[:longitude].blank?

      @latitude =  params[:latitude].to_f
      @longitude = params[:longitude].to_f
      
      @caffes = Caffe.find(:all, :conditions=> ["latitude > ? and latitude < ? and longitude > ? and longitude < ?", @latitude - range, @latitude + range, @longitude - range, @longitude + range])
    
    else
      @caffes = Caffe.find(:all);
    end

    @caffes_json = @caffes.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @caffes}

    end
  end

  def search
    range = 0.01
    
    if !params[:address].blank?

      address_results = Gmaps4rails.geocode(params[:address])
      @latitude =  address_results[0][:lat]
      @longitude = address_results[0][:lng]
      @caffes = Caffe.find(:all, :conditions=> ["latitude > ? and latitude < ? and longitude > ? and longitude < ?", @latitude - range, @latitude + range, @longitude - range, @longitude + range])
    
    else
      @caffes = Caffe.limit(10)
    end

    @caffes_json = @caffes.to_gmaps4rails
    
    respond_to do |format|
      format.html
      format.json {render json: @caffes_json}
    end
  end

  # GET /caffes/1
  # GET /caffes/1.json
  def show
    @caffe = Caffe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @caffe }
    end
  end

  # GET /caffes/new
  # GET /caffes/new.json
  def new
    @caffe = Caffe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @caffe }
    end
  end

  # GET /caffes/1/edit
  def edit
    @caffe = Caffe.find(params[:id])
    @caffes_json = @caffe.to_gmaps4rails
  end

  # POST /caffes
  # POST /caffes.json
  def create
    @caffe = Caffe.new(params[:caffe])

    respond_to do |format|
      if @caffe.save
        format.html { redirect_to @caffe, notice: 'Caffe was successfully created.' }
        format.json { render json: @caffe, status: :created, location: @caffe }
      else
        format.html { render action: "new" }
        format.json { render json: @caffe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /caffes/1
  # PUT /caffes/1.json
  def update
    @caffe = Caffe.find(params[:id])

    respond_to do |format|
      if @caffe.update_attributes(params[:caffe])
        format.html { redirect_to @caffe, notice: 'Caffe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @caffe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caffes/1
  # DELETE /caffes/1.json
  def destroy
    @caffe = Caffe.find(params[:id])
    @caffe.destroy

    respond_to do |format|
      format.html { redirect_to caffes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  # GET /opinions
  # GET /opinions.json
  def index
    @opinions = Opinion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @opinions }
    end
  end

  # GET /opinions/1
  # GET /opinions/1.json
  def show
    @opinion = Opinion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @opinion }
    end
  end

  # GET /opinions/new
  # GET /opinions/new.json
  def new
    @opinion = Opinion.new
    @opinion.caffe_id = params[:caffe_id]
    @caffe = Caffe.find(params[:caffe_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @opinion }
    end
  end

  # GET /opinions/1/edit
  def edit
    @opinion = Opinion.find(params[:id])
  end

  # POST /opinions
  # POST /opinions.json
  def create
    @opinion = Opinion.new(params[:opinion])

    respond_to do |format|
      if @opinion.save
        format.html { redirect_to @opinion.caffe, notice: 'Opinion was successfully created.' }
        format.json { render json: @opinion, status: :created, location: @opinion }
      else
        format.html { render action: "new" }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /opinions/1
  # PUT /opinions/1.json
  def update
    @opinion = Opinion.find(params[:id])

    respond_to do |format|
      if @opinion.update_attributes(params[:opinion])
        format.html { redirect_to @opinion, notice: 'Opinion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opinions/1
  # DELETE /opinions/1.json
  def destroy
    @opinion = Opinion.find(params[:id])
    @opinion.destroy

    respond_to do |format|
      format.html { redirect_to opinions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caffes_helper.rb
module CaffesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/caffes/_form.html.erb
<%= form_for(@caffe) do |f| %>
  <% if @caffe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@caffe.errors.count, "error") %> prohibited this caffe from being saved:</h2>

      <ul>
      <% @caffe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude  %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caffes/_main_view.html.erb
<div class="row">
  <div id="top-rated" class="span4">
    <ul>
      <% @caffes.each do |caffe| %>
        <li class='direction_to'> <%= caffe.name %> 
          <div class='hidden lat_to'> <%= caffe.latitude %></div>
          <div class='hidden lng_to'> <%= caffe.longitude %></div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="span8">
  <%= gmaps("map_options" => { "detect_location" => false, "center_on_user" => false, "zoom" => 4},"markers" => { "data" => @caffes_json }) %>
  </div>
</div>

<script type="text/javascript">
  var keypress_counter = 0;
  $("input#address").keypress(function(e) {
    keypress_counter++;

    var inputAdress = $(this).val();
    var htmlForUpdate = '';
    if(e.keyCode==8)
      keypress_counter--;
    if(inputAdress=='') 
      $("#search-suggestions").html('');
    if(keypress_counter>4){
      var geocoder = new google.maps.Geocoder();
      geocoder.geocode( { 'address': inputAdress}, function(results, status) {

        if (status == google.maps.GeocoderStatus.OK){
          $.each(results, function(key, result){
              htmlForUpdate = htmlForUpdate + "<div id='search-suggesiton-drop-down-item'>" + result.formatted_address + "</div>";
          });
          $("#search-suggestions").html(htmlForUpdate);
          $("#search-suggestions").show();
        }
      });
    }
    
  });  

  $(document).mouseup(function(e) {
    //keypress_counter = 0;
    if($("#search-suggestions").has(e.target).length===0){
      $("#search-suggestions").hide();
    };
  });


  $("#search-suggesiton-drop-down-item").live("click", function(){
    $("#address").val($(this).text());
    $("#search-suggestions").hide();
  });

</script>

app/views/caffes/edit.html.erb
<h1>Editing caffe</h1>

<%= render 'form' %>

<%= gmaps("markers" => { "data" => @caffes_json, "options" => { "draggable" => true }}) %>



<%= link_to 'Show', @caffe %> |
<%= link_to 'Back', caffes_path %>


<%= yield :scripts %>


<script type="text/javascript">

Gmaps.map.HandleDragend = function(pos) {
  var geocoder = new google.maps.Geocoder();
  geocoder.geocode({
    latLng: pos
  }, function(responses) {
    if (responses && responses.length > 0) {
      //alert(responses[0].formatted_address);
      //alert(responses[0].geometry.location.lat());
      $('#caffe_latitude').val(responses[0].geometry.location.lat());
      $('#caffe_longitude').val(responses[0].geometry.location.lng());
    }else {
      alert('Cannot determine address at this location.');
    }
  });
};

Gmaps.map.callback = function() {
  for (var i = 0; i <  this.markers.length; ++i) {
     google.maps.event.addListener(Gmaps.map.markers[i].serviceObject, 'dragend', function() { Gmaps.map.HandleDragend(this.getPosition()) });
  }
  
};        
</script>

app/views/caffes/index.html.erb
<%= render 'main_view' %>


<br />

<%= link_to 'New Caffe', new_caffe_path %>

<%= yield :scripts %>

<script type="text/javascript">
  $(window).load(function(){
    updateTopRatedCaffesListBasedOnPosition();
  });
</script>

app/views/caffes/new.html.erb
<h1>New caffe</h1>

<%= render 'form' %>

<%= link_to 'Back', caffes_path %>

app/views/caffes/search.html.erb
<%= render 'main_view' %>

<%= yield :scripts %>

app/views/caffes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @caffe.name %>
</p>

<p>
  <b>Address:</b>
  <%= @caffe.address %>
</p>

<p>
  <b>Opinions:</b>
  <br>
  <% if @caffe.opinions.blank? %>
    <% # ništa ako prazno %>
  <% else %>
    <% # ima opiniona za kafe %>
    <% @caffe.opinions.each do |opinion| %>
      <em>
        <%= opinion.comment %>
      </em>
      <br>
      Rating: <%= opinion.rating %>
      <br><br>
    <% end %>
  <% end %>
</p>

<%= link_to 'Add new opinion', new_opinion_path(caffe_id: @caffe) %>

<%= link_to 'Edit', edit_caffe_path(@caffe) %> |
<%= link_to 'Back', caffes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nepusacica</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'gmaps4rails' %>
</head>
<body>

<div class="header">
	<div class="container">
		<div class="row">
			<div class="span2 offset6">
				<button id="locator" class=" btn btn-primary ">Lociraj me</button>
		    <%=form_tag(:controller => "caffes", :action => "index", :method => "post") do %>
	        <%= hidden_field_tag(:latitude, "") %>
	        <%= hidden_field_tag(:longitude, "") %>
	        
	      <% end %>
	      
	    </div>

	    <div class="span4">
	      <%=form_tag(:html => {:id => "address_form"}, :controller => "caffes", :action => "search", :method => "post", ) do %>
	      	<%= text_field_tag(:address, "", placeholder: "Trazi u okolini adrese...", :autocomplete => :off) %>
	      <% end %>
	      <div id="search-suggestions"></div>
	    </div>
	  </div>
	</div>
</div>

<div class="container">
    <%= yield %>    
</div>

<script type="text/javascript">
	$("#locator").click(function(){
		updateTopRatedCaffesListBasedOnPosition();
	});
</script>



</body>
</html>

app/views/main/index.html.erb
<div id="logo"></div>
      
<div class="center">
 
  <div class="row">
    <div class="center1">

    </div>

    </div>

<script type="text/javascript">

$(window).load(function(){
  postCurrentUsersLocation();
});

$('#address').keypress(function (e) {
  if (e.which == 13) {
    $('#address_form').submit();
  }
});

</script>

app/views/opinions/_form.html.erb
<%= form_for(@opinion) do |f| %>
  <% if @opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
      <% @opinion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :caffe_id %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/opinions/edit.html.erb
<h1>Editing opinion</h1>

<%= render 'form' %>

<%= link_to 'Show', @opinion %> |
<%= link_to 'Back', opinions_path %>

app/views/opinions/index.html.erb
<h1>Listing opinions</h1>

<table>
  <tr>
    <th>Caffe</th>
    <th>Comment</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @opinions.each do |opinion| %>
  <tr>
    <td><%= opinion.caffe_id %></td>
    <td><%= opinion.comment %></td>
    <td><%= opinion.rating %></td>
    <td><%= link_to 'Show', opinion %></td>
    <td><%= link_to 'Edit', edit_opinion_path(opinion) %></td>
    <td><%= link_to 'Destroy', opinion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Opinion', new_opinion_path %>

app/views/opinions/new.html.erb
<h1>New opinion</h1>
<p>for caffe <%= @caffe.name %></p>
<%= render 'form' %>

<%= link_to 'Back', opinions_path %>

app/views/opinions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Caffe:</b>
  <%= @opinion.caffe_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @opinion.comment %>
</p>

<p>
  <b>Rating:</b>
  <%= @opinion.rating %>
</p>


<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>